/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    DropDown: typeof import('./src/components/wenjuan/DropDown.vue')['default']
    FillBlank: typeof import('./src/components/wenjuan/FillBlank.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect.vue')['default']
    IconX: typeof import('./src/components/IconX.vue')['default']
    MpCheckbox: typeof import('./src/components/mpCheckbox.vue')['default']
    MpInputI18n: typeof import('./src/components/mpInputI18n.vue')['default']
    MpRouterLink: typeof import('./src/components/mpRouterLink.vue')['default']
    MpSwitch: typeof import('./src/components/mpSwitch.vue')['default']
    MpTag: typeof import('./src/components/mpTag.vue')['default']
    MultiChoice: typeof import('./src/components/wenjuan/MultiChoice.vue')['default']
    PasswordStrength: typeof import('./src/components/PasswordStrength.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChoice: typeof import('./src/components/wenjuan/SingleChoice.vue')['default']
    VerifyInput: typeof import('./src/components/VerifyInput.vue')['default']
    XEditer: typeof import('./src/components/wenjuan/XEditer.vue')['default']
  }
}
